[options]
; LOKAL: Biarkan False. 
; SERVER: Ubah jadi True jika sudah diletakkan di belakang Nginx/Reverse Proxy
proxy_mode = False
admin_passwd = AdminKedaiWargaSI2026!
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons